### ISSUE TITLE
Allow a cpanfile to refer to modules in both CPAN and your own DarkPAN(s)

### ISSUE THREAD

**Issue by akarelas** [briandfoy/ncarton#2]
Often companies host their own Perl modules inside their own repositories, at their own custom internal URLs.

It should be possible for a program's cpanfile to contain some distributions from CPAN and some from custom DarkPANs.

**Comment by briandfoy** [comment]
You can already do that. Can you show an example of the problem you're having and what you are trying to do?

**Comment by akarelas** [comment]
I'll try again, after 3 or so years of having tried it, and return here to write about my experience.

**Comment by akarelas** [comment]
Oh, it works! Amazing! Thanks, closing this now, sorry.
